Saavi5Admin.Net/Saavi5Admin/Controllers/CompanyController.cs
using CommonFunctions;
using DataModel.BO;
using DataModel.DA;
using DataModel.Model;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Saavi5Admin.Controllers
{
    [Authorize]
    public class CompanyController : Controller
    {
        private readonly CompanyDA _da;
        private readonly OrderDA _daO;

        public CompanyController()
        {
            _da = new CompanyDA();
            _daO = new OrderDA();
        }

        #region GET: methods

        // GET: Company
        public ActionResult Dashboard()
        {
            GetOrderModel model = new GetOrderModel();
            model.SearchText = "";
            model.AscDesc = "";
            model.SortType = "";
            model.OrderType = "0";
            model.PageNumber = 0;
            model.PageSize = 50;

            ViewBag.Stats = _daO.GetOrderStats();
            ViewBag.Customers = _da.GetTotalCustomers();
            ViewBag.Orders = _daO.ViewOrders(model);
            return View();
        }

        //GET: Get latest added product
        public ActionResult _LatestAddedProduct(string id)
        {
            ProductDA _daP = new ProductDA();
            ViewBag.LatestAddedProduct = _daP.GetLatestAddedProduct(id);
            return PartialView();
        }

        // GET: Customers
        public ActionResult ManageUsers()
        {
            var model = new GetCustomersModel();
            model.PageNumber = 0;
            model.PageSize = 50;
            model.IsRep = false;
            model.SearchText = "";

            ViewBag.Customers = _da.GetAllCustomers(model);

            return View();
        }

        //GET: customer detail
        public ActionResult _CustomerDetail(long? id)
        {
            ViewBag.ProductCategory = _da.GetProductCategory();

            if (id > 0)
            {
                // ViewBag.CustomerChildlist = _da.GetCustomerChildlist(id.To<long>());
                var customerDetails = _da.GetCustomerByID(id.To<long>());
                return PartialView(customerDetails);
            }
            else
            {
                return PartialView(new CustomerBO());
            }
        }

        //GET: new request
        public ActionResult NewRequests()
        {
            var model = new GetCustomersModel();
            model.PageNumber = 0;
            model.PageSize = 50;
            model.IsRep = false;
            model.SearchText = "";

            ViewBag.Customers = _da.GetAllCustomers(model);
            return View();
        }

        //GET: manage customer
        public ActionResult _ManageCustomer(long? id)
        {
            if (id > 0)
            {
                var customerDetails = _da.GetCustomerForEdit(id.To<long>());

                return PartialView(customerDetails);
            }
            else
            {
                return PartialView(new AddEditCustomerBO());
            }
        }

        //GET: manage features
        public ActionResult _ManageFeatures()
        {
            return PartialView();
        }

        //GET: add user
        public ActionResult _AddUser(long? id)
        {
            UserMaster obj = new UserMaster { CustomerID = id };
            return PartialView(obj);
        }

        //GET: delete user
        public ActionResult _DeleteUser(long? id)
        {
            UserMaster obj = new UserMaster { CustomerID = id };
            return PartialView(obj);
        }

        //GET: Pantry list
        public ActionResult _RenamePantryName(long? id)
        {
            //var data = _da.GetPantryList(Convert.ToInt64(id));
            return PartialView();
        }

        // GET: Rep Customers
        public ActionResult ManageRepUser()
        {
            var model = new GetCustomersModel();
            model.PageNumber = 0;
            model.PageSize = 0;
            model.IsRep = true;
            model.SearchText = "";
            ViewBag.IsRepView = true;
            ViewBag.Customers = _da.GetAllCustomers(model);
            return View();
        }

        //GET: rep customer detail
        public ActionResult _RepUserDetail(long? id)
        {
            if (id > 0)
            {
                var customerDetails = _da.GetCustomerByID(id.To<long>());
                return PartialView(customerDetails);
            }
            else
            {
                return PartialView(new CustomerBO());
            }
        }

        //GET: manage customer
        public ActionResult _ManageRepUser(long? id)
        {
            if (id > 0)
            {
                var customerDetails = _da.GetCustomerForEdit(id.To<long>());

                return PartialView(customerDetails);
            }
            else
            {
                return PartialView(new AddEditCustomerBO());
            }
        }

        //GET:My account
        public ActionResult MyAccount()
        {
            var userData = GetLoginData();
            var data = _da.GetUserByID(userData.UserID);
            return View(data);
        }

        //GET:Change password
        public ActionResult _ChangePassword()
        {
            return PartialView(new ChangePasswordModel());
        }

        //GET:Login account
        public ActionResult _LoginAccount(string usertypeids)
        {
            ViewBag.Users = _da.GetUsers(usertypeids);
            return PartialView();
        }

        //GET:Login accounts
        public ActionResult _LoginAccounts(long? id)
        {
            var SelectedUser = _da.GetUserByID(id.To<long>());
            return PartialView(SelectedUser);
        }

        //GET: manage login account
        public ActionResult _ManageLoginAccount(long? id)
        {
            ViewBag.UserType = _da.GetUserType();
            var SelectedUser = new UserBO();
            if (id > 0)
            {
                SelectedUser = _da.GetUserByID(id.To<long>());
            }
            return PartialView(SelectedUser);
        }

        #endregion GET: methods
        #region Get user data from the Authentication ticket

        /// <summary>
        /// Fetch user details that are stored in the auth ticket to be user in the application.
        /// </summary>
        /// <returns></returns>
        private AuthData GetLoginData()
        {
            FormsIdentity formsIdentity = User.Identity as FormsIdentity;

            FormsAuthenticationTicket ticket = formsIdentity.Ticket;
            string userData = ticket.UserData;

            var data = JsonConvert.DeserializeObject<AuthData>(userData);
            return data;
        }

        #endregion Get user data from the Authentication ticket
        #region

        /// <summary>
        /// Get customer paging wise
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult GetCustomersWithPaging(GetCustomersModel model)
        {
            try
            {
                var customers = _da.GetAllCustomers(model);

                return Json(new { Message = "Success", Result = customers });
            }
            catch (Exception ex)
            {
                return Json(new { Message = ex.Message });
            }
        }

        #endregion

        #region

        /// <summary>
        /// Manage customer
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult ManageCustomer(AddEditCustomerBO model)
        {
            try
            {
                var data = _da.ManageCustomer(model);
                return Json(data);
            }
            catch (Exception ex)
            {
                return Json(ex.Message);
            }
        }

        #endregion

        #region

        /// <summary>
        /// Delete customer
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult DeleteCustomer(long id)
        {
            try
            {
                var data = _da.DeleteCustomer(id);
                return Json(data);
            }
            catch (Exception ex)
            {
                return Json(ex.Message);
            }
        }

        #endregion

        #region

        /// <summary>
        /// Change status of Customer
        /// </summary>
        /// <param name="id"></param>
        /// <param name="status"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult SetCustActive(long id, bool status)
        {
            try
            {
                var data = _da.SetCustActive(id, status);
                return Json(data);
            }
            catch (Exception ex)
            {
                return Json(ex.Message);
            }
        }

        #endregion
        #region

        /// <summary>
        /// Get new request
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public JsonResult GetNewRequests()
        {
            try
            {
                var reqs = _da.GetNewRequests();
                return Json(new { Message = "Success", Result = reqs });
            }
            catch (Exception ex)
            {
                return Json(new { Message = ex.Message });
            }
        }

        #endregion

        //#region
        ///// <summary>
        ///// Delete request
        ///// </summary>
        ///// <param name="userID"></param>
        ///// <returns></returns>
        //[HttpPost]
        //public JsonResult delRequest(long userID)
        //{
        //    try
        //    {
        //        var reqs = _da.DeleteRequest(userID);
        //        return Json(reqs);
        //    }
        //    catch (Exception ex)
        //    {

Saavi5Admin.Net/Saavi5Admin/Controllers/ManageCustomerController.cs
using CommonFunctions;
using DataModel.BO;
using DataModel.DA;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Saavi5Admin.Controllers
{   
    [Authorize]
    public class ManageCustomerController : Controller
    {
        private readonly CompanyDA _da;


        public ManageCustomerController()
        {
            _da = new CompanyDA();

        }
        // GET: ManageCustomer
        public ActionResult Index()
        {
            var model = new GetCustomersModel();
            model.PageNumber = 0;
            model.PageSize = 50;
            model.IsRep = false;
            model.SearchText = "";

            ViewBag.Customers = _da.GetAllCustomersByEmail(model);

            return View();
        }


        [HttpPost]
        public JsonResult GetCustomersWithPaging(GetCustomersModel model)
        {
            try
            {
                var customers = _da.GetAllCustomersByEmail(model);

                return Json(new { Message = "Success", Result = customers });
            }
            catch (Exception ex)
            {
                return Json(new { Message = ex.Message });
            }
        }


        //GET: customer detail
        public ActionResult _CustomerDetail(long? id)
        {
            ViewBag.ProductCategory = _da.GetProductCategory();

            if (id > 0)
            {
                // ViewBag.CustomerChildlist = _da.GetCustomerChildlist(id.To<long>());
                var customerDetails = _da.GetMangeCustomerByID(id.To<long>());
                return PartialView(customerDetails);
            }
            else
            {

                return PartialView(new CustomerBO());
            }
        }

        #region manage customer Details
        public JsonResult ManageCustomer(CustomerBO obj)
        {
            try
            {
                var data = _da.ManageCustomer(obj);
                return Json(data);
            }
            catch (Exception ex)
            {
                return Json(ex.Message);
            }
        }
        #endregion
    }
}

Saavi5Admin.Net/Saavi5Admin/Controllers/MasterController.cs
using DataModel.BO;
using DataModel.DA;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Saavi5Admin.Controllers
{
    [Authorize(Roles = "SuperAdmin")]
    public class MasterController : Controller
    {
        private readonly AccountDA _da;
        public MasterController()
        {
            _da = new AccountDA();
        }

        #region Get user data from the Authentication ticket
        /// <summary>
        /// Fetch user details that are stored in the auth ticket to be user in the application.
        /// </summary>
        /// <returns></returns>
        private AuthData GetLoginData()
        {
            FormsIdentity formsIdentity = User.Identity as FormsIdentity;

            FormsAuthenticationTicket ticket = formsIdentity.Ticket;
            string userData = ticket.UserData;

            var data = JsonConvert.DeserializeObject<AuthData>(userData);
            return data;
        }
        #endregion

        #region
        /// <summary>
        ///  Common Top Header
        /// </summary>
        /// <returns></returns>
        [AllowAnonymous]
        public ActionResult _TopHeader()
        {
            //FormsIdentity formsIdentity = User.Identity as FormsIdentity;
            //if (formsIdentity != null)
            //{
            return PartialView(GetLoginData());
            //}
            //else {return RedirectToAction("Login", "Account"); }
        }
        #endregion

        #region 
        /// <summary>
        /// Fetch Admin and Main features for a user.
        /// </summary>
        /// <returns></returns>
        public ActionResult ManagedFeatures()
        {
            var features = _da.GetAdminAndMainFeatures();

            ViewBag.AdminFeatures = features.AdminFeatures;
            ViewBag.MainFeatures = features.MainFeatures;

            return View();
        }
        #endregion

        #region 
        /// <summary>
        /// Update Admin or Main features for a customer.
        /// </summary>
        /// <param name="column"></param>
        /// <param name="value"></param>
        /// <param name="type"></param>
        /// <returns></returns>
        public JsonResult UpdateAdminOrMainFeature(string column, string value, string type)
        {
            string result = _da.UpdateAdminOrMainFeature(column, value == "False" ? "0" : "1", type == "admin" ? "adminfeaturesmaster" : "mainfeaturesmaster");

            return Json(result);
        }
        #endregion       
    }
}

Saavi5Admin.Net/Saavi5Admin/Views/Master/ManagedFeatures.cshtml
@{
    ViewBag.Title = "Manage Features";

    List<DataModel.BO.FeaturesMasterBo> adminFeatures = ViewBag.AdminFeatures;
    List<DataModel.BO.FeaturesMasterBo> mainFeatures = ViewBag.MainFeatures;
}

@section scripts{
    <script>
        $(function () {
            $(".checkbox label").each(function () {
                $(this).html($(this).html().replace(/([a-z])([A-Z])/g, '$1 $2'));
            });
        });
        function updateMainOrAdminFeatures(ctrl) {
            startLoading();
            var data = {
                column: $(ctrl).data('column'),
                value: $(ctrl).prop('checked'),
                type: $(ctrl).data('type')
            }
            $.ajax({
                type: "POST",
                contentType: "application/json; charset=utf-8",
                dataType:'json',
                url: '@Url.Action("UpdateAdminOrMainFeature","Master")',
                data: JSON.stringify(data),
                success: function (response) {
                    stopLoading();
                }
            });
        }

        //function saveCurrency(ctrl) {
        //    var currency = $(ctrl).val();
        //    alert(currency);
        //}
    </script>
}

<div class="tab-content">
    <div id="admin-features" class="section full-height tab-pane active" role="tabpanel">
        <div class="row full-height">
            <div class="col-md-12 col full-height">
                <div class="flex-column full-height">
                    <div class="well table">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="row login">
                                    @for (int i = 0; i < adminFeatures.Count; i++)
                                    {
                                        if (i == 0 || i == 12 || i == 24 || i == 36)
                                        {
                                            @Html.Raw("<div class='col-sm-3 col'>")
                                        }
                                        <div class="checkbox right">
                                            <input type="checkbox" onchange="updateMainOrAdminFeatures(this);" data-column="@adminFeatures[i].Name" id="chk_@i" checked="@adminFeatures[i].Selected" data-type="admin" />
                                            <label class="lbl_@i" for="chk_@i">@adminFeatures[i].Name.Replace("Is", "") <i title="@Html.AttributeEncode(adminFeatures[i].Description)" data-toggle="tooltip" class="info fa fa-info-circle" style="/*font-size:15px;color:#3abeee;text-decoration:none;padding-left:5px;*/"> </i></label>
                                        </div>
                                        if (i == 11 || i == 23 || i == 35 || i == adminFeatures.Count - 1)
                                        {
                                            @Html.Raw("</div>")
                                        }
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="main-features" class="section full-height tab-pane" role="tabpanel">
        <div class="row full-height">
            <div class="col-md-12 col full-height">
                <div class="flex-column full-height">
                    <div class="well table">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="row login">
                                    @for (int i = 0; i < mainFeatures.Count; i++)
                                    {
                                        if (i == 0 || i == 12 || i == 24 || i == 36)
                                        {
                                            @Html.Raw("<div class='col-sm-3 col'>")
                                        }
                                        <div class="checkbox right">
                                            <input type="checkbox" onchange="updateMainOrAdminFeatures(this);" data-column="@mainFeatures[i].Name" id="chkm_@i" checked="@mainFeatures[i].Selected" data-type="main" />
                                            <label for="chkm_@i">@mainFeatures[i].Name.Replace("Is", "") <i title="@Html.AttributeEncode(mainFeatures[i].Description)" data-toggle="tooltip" class="info fa fa-info-circle"> </i></label>
                                        </div>
                                        @*if (i == mainFeatures.Count - 1)
                                        {
                                        <div class="col-md-12" style="padding:0px">
                                            <div class="col-md-8" style="padding:0px">
                                                <b style="color:#636363">Currency</b>
                                            </div>
                                            <div class="col-md-4" style="padding:0px">
                                                <select style="padding: 1px 13px 1px !important;" onchange="saveCurrency(this)">
                                                    <option value="$">$ Dollar</option>
                                                    <option value="¥">¥ Yen</option>
                                                </select>
                                            </div>
                                            
                                        </div>
                                           
                                        }*@
                                        if (i == 11 || i == 23 || i == 35 || i == mainFeatures.Count - 1)
                                        {
                                            @Html.Raw("</div>")
                                        }
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Saavi5Admin.Net/Saavi5Admin/Views/Master/_HeaderPartial.cshtml
<nav id="bs-navbar" class="">
    <div class="navigation" id="navigation">
        <ul class="nav navbar-nav">
            <li><a href="javascript:;"><img src="~/content/images/dashboard.png"></a></li>
            <li class="active" role="presentation">
                <a href="#admin-features" data-toggle="tab">ADMIN FEATURES</a>
                <div class="tab">
                    <div class="pull-left">
                        <h1>Admin Features</h1>
                    </div>
                </div>
            </li>
            <li>
                <a href="#main-features" data-toggle="tab">MAIN FEATURES</a>
                <div class="tab">
                    <div class="pull-left">
                        <h1>Main Features</h1>
                    </div>
                </div>
            </li>
        </ul>
    </div>
</nav>

Saavi5Admin.Net/Saavi5Admin/Views/Master/_TopHeader.cshtml
@model DataModel.BO.AuthData

@{
    string role = "CompanyAdmin";
    if (User.IsInRole("SuperAdmin"))
    {
        role = "SuperAdmin";
    }
    else if (User.IsInRole("PODAdmin"))
    {
        role = "PODAdmin";
    }
    else if (User.IsInRole("Rego"))
    {
        role = "Rego";
    };
}
<div class="header">
    <div class="pull-left">
        @if (role == "SuperAdmin")
        {
            <a class="logo" href="javascript:;"><img src="~/content/images/logo.png"></a>
        }
        else
        {
            <a class="logo" href="@Url.Action("Dashboard","Company")"><img src="~/content/images/logo.png"></a>
        }
    </div>
    <div class="pull-right">
        @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
        { }
        <div class="client">
            <h3 id="user">@Model.Name</h3>
            <ul id="toggle-div">
                @if (role == "CompanyAdmin")
                {
                    <li><a href="@Url.Action("MyAccount", "Company")">My Account</a></li>
                    <li><a href="@Url.Action("Index", "ManageCustomer")">Troubleshoot Login</a></li>
                }
                <li><a href="javascript:document.getElementById('logoutForm').submit()">Logout</a></li>
            </ul>
        </div>
    </div>
    <div class="break"></div>
</div>

<script>
    $("#user").click(function () {
        $("#toggle-div").slideToggle(),
            $(this).toggleClass("active"),
            $("#toggle-div").css("z-index","99999");
            $("#toggle-div li a").on("click", function () {
                $("#toggle-div").slideUp();
            });
    });
</script>