Saavi5Admin.Net/Saavi5Admin/Areas/Saavi5POD/Controllers/DeliveriesController.cs
using DataModel.BO;
using DataModel.DA;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Saavi5Admin.Areas.Saavi5POD.Controllers
{
    public class DeliveriesController : Controller
    {
        private readonly DeliveriesDA _da;

        public DeliveriesController()
        {
            _da = new DeliveriesDA();
        }

        #region GET methods

        // GET: Saavi5POD/Deliveries
        public ActionResult Deliveries()
        {
            //var model = new GetListModel();
            //model.PageNumber = 0;
            //model.PageSize = 50;
            //model.SearchText = "";
            //ViewBag.Customer = _da.GetAllCustomer(model);
            return View();
        }

        //GET: Customer
        public ActionResult _Customers(string id)
        {
            GetListModel model = new GetListModel { SearchText = id };
            //var model = new GetListModel();
            //model.PageNumber = 0;
            //model.PageSize = 50;
            //model.SearchText = "";
            ViewBag.Customer = _da.GetAllCustomer(model);
            return PartialView();
        }

        //GET: Orders
        public ActionResult _Orders(int? id, int orderid, string type, DateTime? delDate)
        {
            ViewBag.Orders = _da.GetAllOrderByCustomerID(id, orderid, type, delDate);
            return PartialView();
        }

        //GET: Order detail
        public ActionResult _OrderDetail(int id)
        {
            var data = _da.GetOrderDeliveryDetail(id);
            return View(data);
        }

        //GET: Deliveries By Invoice
        public ActionResult DeliveriesByInvoice()
        {
            // ViewBag.Orders = _da.GetAllOrderByCustomerID(0, 0);
            return View();
        }

        //GET: Issues
        public ActionResult Issues()
        {
            return View();
        }

        //GET: Issues By Invoice
        public ActionResult IssuesByInvoice()
        {
            // ViewBag.Orders = _da.GetAllOrderByCustomerID(0, 0);
            return View();
        }

        //GET: deliveries by driver
        public ActionResult DeliveriesByDriver()
        {
            return View();
        }

        //GET: Delivery images
        public ActionResult _DeliveryImages(int id, bool hasissue)
        {
            ViewBag.DeliveryImages = _da.GetDeliveryImages(id, hasissue);
            return PartialView();
        }

        //GET: pod copy
        public ActionResult PODcopy()
        {
            return View();
        }

        //GET: POD all customers
        public ActionResult _PODAllCustomers(string id)
        {
            GetListModel model = new GetListModel { SearchText = id };
            ViewBag.Customer = _da.GetAllCustomer(model);
            return PartialView();
        }

        //GET POD all orders by customer
        public ActionResult _PODAllOrdersByCustomer(int? id)
        {
            ViewBag.Orders = _da.GetPODAllOrdersByCustomerID(id);
            return PartialView();
        }

        //GET: Get all existing driver with assigned vehicle
        public ActionResult _AssignedDrivers(string id)
        {
            GetListModel model = new GetListModel { SearchText = id };
            ViewBag.AssignedDrivers = _da.GetAllAssignedDrivers(model);
            return PartialView();
        }

        //GET: Get all assigned orders
        public ActionResult _AssignedOrders(int id, string runno, string suburb = "")
        {
            ViewBag.AssignedOrders = _da.GetAllPendingOrders(id, runno, suburb);
            return PartialView();
        }

        //GET: Get all unassigned orders
        public ActionResult _UnassignedOrderList(int id, string runno, string suburb = "")
        {
            ViewBag.UnassignedOrders = _da.GetAllPendingOrders(id, runno, suburb);
            return PartialView();
        }

        //GET: Order short detail
        public ActionResult _OrderShortDetail(int id)
        {
            var data = _da.GetOrderDeliveryDetail(id);
            return View(data);
        }

        //GET: manage delivery date
        public ActionResult _ManageDelDate(int id, DateTime? delDate)
        {
            DeliveryDateBO model = new DeliveryDateBO();
            model.orderID = id;
            model.PrevDeliveryDate = delDate;
            return PartialView(model);
        }

        //GET: manage reassign orders to another drivers
        public ActionResult _ReassignOrders()
        {
            GetListModel model = new GetListModel();
            ViewBag.AssignedDrivers = _da.GetAllAssignedDrivers(model);
            return PartialView();
        }

        //GET: get _FieldChooser
        public ActionResult _FieldChooser()
        {
            //ViewBag.RunNoList = _da.GetCustomerRunNo();
            return PartialView();
        }

        //GET: Warehouse
        public ActionResult Warehouse()
        {
            var runs = _da.DeliveryRunsByWarehouse("Brisbane");
            var subs = _da.GetSuburbsByDeliveryRuns(runs[0]);
            ViewBag.Suburbs = subs;

            ViewBag.DeliveryRuns = runs;
            GetListModel model = new GetListModel();
            ViewBag.AssignedDrivers = _da.GetAllAssignedDrivers(model);
            ViewBag.AssignedOrders = _da.GetAllPendingOrders(-1, runs[0], "");
            ViewBag.UnassignedBySuburb = _da.GetAllPendingOrders(0, runs[0], subs[0]);
            return View();
        }

        //GET: Get all assigned orders
        public ActionResult _AssignedOrdersSuburbs(int id, string runno = "", string suburb = "")
        {
            ViewBag.AssignedOrders = _da.GetAllPendingOrders(id, runno, suburb);
            return PartialView();
        }

        public ActionResult _UnassignedBySuburbs(int id, string runno = "", string suburb = "")
        {
            ViewBag.UnassignedBySuburb = _da.GetAllPendingOrders(id, runno, suburb);
            return PartialView();
        }

        #endregion GET methods

        #region Get customer by search

        [HttpPost]
        public JsonResult GetAllCustomer(string id)
        {
            try
            {
                GetListModel model = new GetListModel { SearchText = id };
                var data = _da.GetAllCustomer(model);
                return Json(new { Message = "Success", Result = data });
            }
            catch (Exception ex)
            {
                return Json(new { Message = ex.Message });
            }
        }

        #endregion Get customer by search

        #region Assign order to driver

        [HttpPost]
        public JsonResult AssignOrderToDriver(int id, string orderIDs, string type)
        {
            try
            {
                var data = _da.AssignOrderToDriver(id, orderIDs, type);
                return Json(new { Message = "Success", Result = data });
            }
            catch (Exception ex)
            {
                return Json(new { Message = ex.Message });
            }
        }

        #endregion Assign order to driver

        #region Manage Order's Delivery date

        [HttpPost]
        public JsonResult ManageDelDate(DeliveryDateBO model)
        {
            try
            {
                var data = _da.ManageDelDate(model.orderID, model.DeliveryDate);
                return Json(data);
            }
            catch (Exception ex)
            {
                return Json(ex.Message);
            }
        }

        #endregion Manage Order's Delivery date

        #region Get Delivery runs by warehosue

        [HttpPost]
        public JsonResult GetDeliveryRunByWarehouse(string warehouse)
        {
            try
            {
                var res = _da.DeliveryRunsByWarehouse(warehouse);
                var suburbs = _da.GetSuburbsByDeliveryRuns(res[0]);
                return Json(new
                {
                    Runs = res,
                    Subs = suburbs
                });
            }
            catch (Exception ex)
            {
                return Json(ex.Message);
            }
        }

        #endregion Get Delivery runs by warehosue

        #region Get Suburbs by delivery runs

        [HttpPost]
        public JsonResult GetSuburbsByDeliveryRuns(string run)
        {
            try
            {
                var suburbs = _da.GetSuburbsByDeliveryRuns(run);
                return Json(suburbs);
            }
            catch (Exception ex)
            {
                return Json(ex.Message);
            }
        }

        #endregion Get Suburbs by delivery runs

        //GET: manage reassign orders to another drivers
        public ActionResult _ReassignWarehouseOrders()
        {
            GetListModel model = new GetListModel();
            ViewBag.AssignedDrivers = _da.GetAllAssignedDrivers(model);
            return PartialView();
        }
    }
}

Saavi5Admin.Net/Saavi5Admin/Areas/Saavi5POD/Controllers/DriverController.cs
using DataModel.BO;
using DataModel.DA;
using DataModel.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Saavi5Admin.Areas.Saavi5POD.Controllers
{
    public class DriverController : Controller
    {
        private readonly DriverDA _da;
        public DriverController()
        {
            _da = new DriverDA();
        }
        #region GET methods
        // GET: Driver
        public ActionResult ManageDrivers()
        {
            var model = new GetListModel();
            model.PageNumber = 0;
            model.PageSize = 50;
            model.SearchText = "";

            var data = _da.GetAllDrivers(model);
            ViewBag.Driver = data;
            ViewBag.Vehicle = _da.GetAllVehicles(model).Where(x=>x.IsDeleted==false).ToList();
            return View();
        }
        // GET:  manage Driver
        public ActionResult _ManageDriver(int? id)
        {
            if (id > 0)
            {
                var data = _da.GetUserByID(id);
                return PartialView(data);
            }
            else
            {
                return PartialView(new UserBO());
            }
        }
        //GET: driver detail
        public ActionResult _DriverDetail(int? id)
        {
            var data = _da.GetUserByID(id);
            return PartialView(data);
        }

        //GET: vehicle
        public ActionResult ManageVehicle()
        {
            var model = new GetListModel();
            model.PageNumber = 0;
            model.PageSize = 50;
            model.SearchText = "";

            var data = _da.GetAllVehicles(model);
            ViewBag.Vehicle = data;
            ViewBag.Driver = _da.GetAllDrivers(model);
            return View();
        }
        //GET: manage vehicle
        public ActionResult _ManageVehicle(int? id)
        {
            if (id > 0)
            {
                var data = _da.GetVehicleByID(id);
                var runs = _da.GetDeliveryRuns();

                ViewBag.Runs = runs;

                return PartialView(data);
            }
            else
            {
                var data = new VehicleBO();
                data.IsFixturesFittingOK = data.IsLightSignalOK = data.IsTyreConditionOK = data.IsVehicleConditionOK = data.IsWindscreenOK = true;
                var runs = _da.GetDeliveryRuns();

                ViewBag.Runs = runs;
                return PartialView(data);
            }

        }
        //GET: vehicle detail
        public ActionResult _VehicleDetail(int? id)
        {
            var data = _da.GetVehicleByID(id);
            return PartialView(data);
        }

        #endregion

        #region Search vehicle   
        [HttpPost]
        public JsonResult GetAllVehicle(string id, string type)
        {
            try
            {
                GetListModel model = new GetListModel { SearchText = id };
                if (type == "d")
                {
                    return Json(new { Message = "Success", Result = _da.GetAllDrivers(model) });
                }
                else { return Json(new { Message = "Success", Result = _da.GetAllVehicles(model) }); }

            }
            catch (Exception ex)
            {
                return Json(new { Message = ex.Message });
            }
        }
        #endregion

        #region Manage Driver
        /// <summary>
        ///  Manage Driver
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult ManageDrivers(UserBO model)
        {
            try
            {
                if (Request.Files["fuLicense"] != null)
                {
                    model.licenceImage = Request.Files["fuLicense"];
                }
                if (Request.Files["fuimage"] != null)
                {
                    model.driverImage = Request.Files["fuimage"];
                }
                var data = _da.ManageDriver(model);
                ViewData["Message"] = data;
                //return RedirectToAction("ManageDrivers");
                var model2 = new GetListModel();
                model2.PageNumber = 0;
                model2.PageSize = 50;
                model2.SearchText = "";

                var data2 = _da.GetAllDrivers(model2);
                ViewBag.Driver = data2;
                ViewBag.Vehicle = _da.GetAllVehicles(model2);
                return View();
                //  return PartialView(model);
            }
            catch (Exception ex)
            {
                ViewData["Message"] = ex.Message;
                var model2 = new GetListModel();
                model2.PageNumber = 0;
                model2.PageSize = 50;
                model2.SearchText = "";

                var data2 = _da.GetAllDrivers(model2);
                ViewBag.Driver = data2;
                ViewBag.Vehicle = _da.GetAllVehicles(model2);
                return View();
            }
        }
        #endregion

        #region Assign Vehicle To Driver
        public JsonResult AssignVehicleToDriver(int vID, int dID)
        {
            try
            {
                var data = _da.AssignVehicleToDriver(vID, dID);
                return Json(data);
            }
            catch (Exception ex)
            {
                return Json(ex.Message);
            }
        }
        #endregion

        #region Manage Vehicle
        [HttpPost]
        public JsonResult ManageVehicle(VehicleBO model)
        {
            try
            {
                var data = _da.ManageVehicle(model);
                return Json(data);
            }
            catch (Exception ex)
            {
                return Json(ex.Message);
            }

        }
        #endregion

        #region Delete vehicle
        [HttpPost]
        public JsonResult DeleteVehicle(int vehicleID, bool val)
        {
            try
            {
                var data = _da.DeleteVehicle(vehicleID, val);
                return Json(data);
            }
            catch (Exception ex)
            {
                return Json(ex.Message);
            }
        }
        #endregion


    }
}

Saavi5Admin.Net/Saavi5Admin/Areas/Saavi5POD/Controllers/TrackingController.cs
using DataModel.BO;
using DataModel.DA;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Saavi5Admin.Areas.Saavi5POD.Controllers
{
    public class TrackingController : Controller
    {
        private readonly TrackingDA _da;
        public TrackingController()
        {
            _da = new TrackingDA();
        }
        // GET: Saavi5POD/Tracking
        public ActionResult Tracking()
        {            
            return View();
        }
        //GET: vehicle list
        public ActionResult _VehicleList(string id)
        {
            GetListModel model = new GetListModel();
            model.SearchText = id;
            ViewBag.Vehicle = _da.GetAllVehicle(model);
            return PartialView();
        }
        //GET: vehicle location
        public ActionResult _VehicleLocation(long? id)
        {
            ViewBag.DeliveryTrackList = _da.GetDeliveryTrackList(id);
            return PartialView();
        }
    }
}

Saavi5Admin.Net/Saavi5Admin/Areas/Saavi5POD/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width" />
    <meta name="format-detection" content="telephone=no" />
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:300,400|Roboto:300,400,500,700" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/css/bootstrap.min.css")" media="screen">
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/css/stylesPOD.css")" media="screen">
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/css/jquery.mCustomScrollbar.min.css")" />
    <link href="~/Content/css/bootstrap-datepicker.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="@Url.Content("~/Content/css/jquery-confirm.min.css")" rel="stylesheet" />
    @*<link href="~/Content/css/jkanban.min.css" rel="stylesheet" />*@
    <title>@System.Configuration.ConfigurationManager.AppSettings["WEBSITE_NAME"] POD | @ViewBag.Title</title>
</head>
<body class="main">
    <div class="canvas">
        <div class="outer-header" id="outerHeader">
        </div>
        <div class="inner-body">
            <div class="container-fluid">
                <div class="navbar navbar-static-top bs-docs-nav" role="banner">
                    <div class="navbar-header">
                        <button id="nav-toggle" class="navbar-toggle collapsed back-to-top" data-toggle="#form" type="button">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <nav id="bs-navbar" class="">
                        <div class="navigation" id="navigation">
                            <ul class="nav navbar-nav" id="mainNav">
                                <li data-href="home">
                                    <a href='@Url.Action("Dashboard","Home")'><img src="~/Content/images/dashboard.png"></a>
                                    <div class="tab">
                                        <div class="pull-left">
                                            <h1>Dashboard</h1>
                                        </div>
                                        <div class="pull-right">
                                            <div class="search">
                                                <fieldset id="deliveries-pick-date_icons">
                                                    <input id="txtDashboardSearch" name="txtDashboardSearch" type="text" placeholder="Search by vehicle" />
                                                    <input id="btnDashboardSearch" name="btnDashboardSearch" type="submit" onclick="GetVehiclesDeliveryStatus();" />
                                                </fieldset>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li data-href="driver">
                                    @Html.ActionLink("MANAGE DRIVERS", "ManageDrivers", "Driver")
                                    <div class="tab">
                                        <div class="pull-left">
                                            <h1>Manage Drivers</h1>
                                            <div class="btn-group" id="divdrivermenu">
                                                <a data-href="managedrivers" href="@Url.Action("ManageDrivers","Driver")" class="btn-border active">Drivers</a>
                                                <a data-href="managevehicle" href="@Url.Action("ManageVehicle","Driver")" class="btn-border">Vehicles</a>
                                            </div>
                                        </div>
                                        <div class="pull-right">
                                            <div class="search">
                                                <fieldset id="deliveries-pick-date_icons1">
                                                    <input id="txtDriverSearch" name="txtDriverSearch" type="text" placeholder="Search By Drivers" />
                                                    <input id="btnDriverSearch" name="btnDriverSearch" type="submit" data-type="d" onclick="GetAllDriVeh(this);" />
                                                </fieldset>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li data-href="deliveries">
                                    @Html.ActionLink("DELIVERIES", "DeliveriesByDriver", "Deliveries")
                                    <div class="tab">
                                        <div class="pull-left">
                                            <h1>Deliveries</h1>
                                            <div class="btn-group" id="divDLmenus">
                                                <a data-href="deliveries" href='@Url.Action("DeliveriesByDriver","Deliveries")' class="btn-border  active">View</a>
                                                <a data-href="issues" href='@Url.Action("Issues","Deliveries")' class="btn-border">Issues</a>
                                                <div class="input-group date hidden" data-provide="datepicker" id="divDelDate">
                                                    <input id="txtPickDeliveryDate" name="txtPickDeliveryDate" type="text" class="form-control datepicker" placeholder="pick deliveries date" onchange="GetSearchedOrderList();">
                                                    <div class="input-group-addon" id="deliveries-pick-date_icons">
                                                        <i class="fa fa-calendar-check-o" aria-hidden="true"></i>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="pull-right">
                                            <div class="search">
                                                <fieldset id="deliveries-pick-date_icons">
                                                    <input id="txtDeliverySearch" name="txtDeliverySearch" type="text" placeholder="Search deliveries by customer name" />
                                                    <input id="btnDeliverySearch" name="btnDeliverySearch" type="submit" onclick="GetCustomers();" />
                                                </fieldset>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li data-href="tracking">
                                    @Html.ActionLink("TRACKING", "Tracking", "Tracking")
                                    <div class="tab">
                                        <div class="pull-left">
                                            <h1>Tracking</h1>
                                        </div>
                                        <div class="pull-right">
                                            <div class="search">
                                                <fieldset id="deliveries-pick-date_icons">
                                                    <input id="txtTrackSearch" name="txtTrackSearch" type="text" placeholder="Search by vehicle" />
                                                    <input type="submit" onclick="GetAllVehicle();" />
                                                </fieldset>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li data-href="message">
                                    @Html.ActionLink("MESSAGES", "SendMessage", "Message")
                                    <div class="tab">
                                        <div class="pull-left">
                                            <h1>Messages</h1>
                                        </div>
                                        <div class="pull-right">
                                            <div class="search">
                                                <fieldset id="deliveries-pick-date_icons">
                                                    <input id="txtMessageSearch" name="txtMessageSearch" type="text" placeholder="Search By Driver" />
                                                    <input type="submit" onclick="GetAllDriver();" />
                                                </fieldset>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </nav>
                </div>
                <div class="content">
                    @RenderBody()
                </div>
            </div>
        </div>
        <div id="divLoading" style="display:none;">
            <img src="~/Content/images/loading.gif" height="50" />
        </div>
    </div>

    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">

    @*<script type="text/javascript" src="@Url.Content("~/Scripts/main_script.js")"></script>
        <script type="text/javascript" src="@Url.Content("~/Scripts/bootstrap.min.js")"></script>
        <script type="text/javascript" src="@Url.Content("~/Scripts/tableHeadFixer.js")"></script>
        <script type="text/javascript" src="@Url.Content("~/Scripts/scripts.js")"></script>*@
    @Scripts.Render("~/Scripts")
    <script src="@Url.Content("~/Scripts/stacktable.min.js")"></script>
    @RenderSection("podScripts", required: false)
    <script>
        $(function () {
            var controller = '@HttpContext.Current.Request.RequestContext.RouteData.Values["controller"].ToString().ToLower()';
           var action = '@HttpContext.Current.Request.RequestContext.RouteData.Values["action"].ToString().ToLower()';
           $('ul#mainNav li').each(function () {
                if (action != 'dashboard') {
                    $('body').removeClass();
                }
                if ($(this).data('href').toLowerCase() == controller) {
                    $(this).addClass('active');
                }
                if (controller === 'deliveries') {
                    $('#divDelMenus').find('a').removeClass('active');
                    $('#divDelMenus').find('a[data-href="' + action + '"]').addClass('active');
                    if (action == "issues" || action == "issuesbyinvoice") {
                        $('#divDLmenus').find('a').removeClass('active');
                        $('#divDLmenus').find('a[data-href="issues"]').addClass('active');
                    }
                }
                if (controller === 'driver') {
                    $('#divdrivermenu').find('a').removeClass('active');
                    $('#divdrivermenu').find('a[data-href="' + action + '"]').addClass('active');
                }
           });
           $("#outerHeader").load('@Url.Action("_TopHeader","Home")');

           //$('.datepicker').datepicker({
           //    startDate: '-d',
           //    autoclose: true

           //});
           $('.card-table').cardtable();
          $("#divDelDate").hide();
            //
           $(".tab div.search input[type='text']").on('keyup', function (e) {          
               if (e.keyCode == 13) {
                   $(this).next("input[type='submit']").click();
               }
           });
        });        
    </script>
</body>
</html>

Saavi5Admin.Net/Saavi5Admin/Areas/Saavi5POD/Views/Shared/_TopHeader.cshtml
@model DataModel.BO.AuthData


<div class="header">
    <div class="pull-left">
        <a class="logo" href="@Url.Action("Dashboard","Home")"><img src="~/Content/images/logo.png"></a>
    </div>
 <div style="float:left;"><h1 style="padding-top:15%;">PROOF OF DELIVERY</h1></div>
    @*<h1 class="delivery_text-header">PROOF OF DELIVERY</h1>*@
    <div class="pull-right">
        @using (Html.BeginForm("LogOff", "../Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
        { }
        <div class="client">
            <h3 id="user">@Model.Name</h3>
            <ul id="toggle-div">
                @*<li><a href="#">Profile</a></li>*@
                <li><a href="javascript:document.getElementById('logoutForm').submit()">Logout</a></li>
            </ul>
        </div>
    </div>
    <div class="break"></div>
</div>
<script>
    $("#user").click(function () {
        $("#toggle-div").slideToggle(),
            $(this).toggleClass("active"),
            $("#toggle-div li a").on("click", function () {
                $("#toggle-div").slideUp()
            });
    });
</script>