Saavi5Admin.Net/Saavi5Admin/Controllers/PaymentController.cs
using DataModel.BO;
using DataModel.DA;
using DataModel.Model;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace Saavi5Admin.Controllers
{
    [Authorize(Roles = "CompanyAdmin,SuperAdmin")]
    public class PaymentController : Controller
    {
        private readonly PaymentDA _da;


        public PaymentController()
        {
            _da = new PaymentDA();

        }

        #region Connect Stripe Account
        /// <summary>
        /// Connect Stripe Account
        /// </summary>
        /// <param name="code"></param>
        /// <returns></returns>
        [AllowAnonymous]
        public ActionResult ConnectAccount(string code, string client_id = "")
        {
            if (code.Length > 5 && ConfigurationManager.AppSettings["StripeConnectedAccountID"] == "")
            {
                var res = _da.ConnectAccount(code, client_id);
                ViewBag.IsConnected = res.Connected;
                ViewBag.ConnectedAccountId = res.AccountID;
                ConfigurationManager.AppSettings["StripeConnectedAccountID"] = res.AccountID;
                ViewBag.Error = res.Error;
            }
            else
            {
                ViewBag.IsConnected = false;
                ViewBag.Error = "Invalid request.";
            }
            return PartialView();
        }
        #endregion Connect Stripe Account

        #region Capture Payment
        /// <summary>
        /// Capture Payment
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        public ActionResult _CapturePayment(long id, double orderTotal, double? authorizedAmt, long? UserID)
        {
            PaymentBO model = new PaymentBO();
            model.CartID = id;
            model.CustomerID = 0;
            model.UserID = UserID;
            var paymentDetail = _da.GetPaymentDetail(id);
            if (!string.IsNullOrEmpty(paymentDetail))
            {
                model.PaymentReference = paymentDetail;
            }
            ViewBag.OrderTotal = orderTotal;
            ViewBag.CapturePrice = authorizedAmt;
            return PartialView(model);
        }
        #endregion

        #region 
        /// <summary>
        /// Capture Payment
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult CapturePayment(PaymentBO model)
        {
            try
            {
                var result = _da.CapturePayment(model);
                return Json(result);
            }
            catch (Exception ex)
            {
                return Json(ex.Message);
            }
        }
        #endregion

        #region 
        /// <summary>
        /// Refund Payment
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult _RefundPayment(long id, double orderTotal, double? authorizedAmt, long? UserID,long? CustomerID, int Status, int Click)
        {
            RefundBO model = new RefundBO();
            model.CartID = id;
            model.CustomerID = CustomerID!=null?Convert.ToInt64(CustomerID): 0;
            if(CustomerID!=null)
            {
                var customer= _da.GetCustomerDetail(id,CustomerID);
                if(customer!=null && customer.Email!=null)
                {
                    model.CustomerEmail = customer.Email;
                    model.CustomerName = customer.CustomerName;
                }
            }
            model.UserID = UserID;
            ViewBag.OrderTotal = orderTotal;
            ViewBag.CapturePrice = authorizedAmt;
            ViewBag.RefundAmount = 0.00;
            ViewBag.RefundStatus = Status;
            model.TotalCaptureAmount = orderTotal;
            model.PaymentClick = Click;
            model.ShowAmount = "";
            if (Click == 2)
            {
                model.Amount = authorizedAmt != null ? Math.Round(Convert.ToDouble(authorizedAmt), 2) : 0;
                model.ShowAmount= authorizedAmt != null ? String.Format("{0:$#,##0.00;($#,##0.00)}", Math.Round(Convert.ToDouble(authorizedAmt), 2)) : "";
            }
            if (Status == 1)
            {
                var striperefunddetail = _da.GetRefundDetail(id);
                if (striperefunddetail != null && striperefunddetail.LogID != 0 && !string.IsNullOrEmpty(Convert.ToString(striperefunddetail.LogID)))
                {
                    ViewBag.RefundAmount = striperefunddetail.RefundAmount;
                    ViewBag.OrderTotal = striperefunddetail.CaptureAmount;
                    model.RefundCreatedOn = striperefunddetail.CreatedOn.Value.ToString("dd/MM/yyyy");
                    model.RefundCreatedTime = striperefunddetail.CreatedOn.Value.ToString("hh:mm tt");
                    model.RefundReference = striperefunddetail.RefundId;
                }
                else
                {
                    ViewBag.OrderTotal = !string.IsNullOrEmpty(Convert.ToString(orderTotal)) ? 0.00 : orderTotal;
                    ViewBag.RefundAmount = 0.00;
                    ViewBag.CapturePrice = !string.IsNullOrEmpty(Convert.ToString(authorizedAmt)) ? 0.00 : authorizedAmt;
                }
            }
            var stripedetail = _da.GetRefundPaymentDetail(id);
            if (stripedetail != null && stripedetail.ID != 0 && !string.IsNullOrEmpty(Convert.ToString(stripedetail.ID)))
            {
                model.PaymentReference = stripedetail.StripeChargeID;
                model.Netpayment = stripedetail.NetAmount;
                model.TotalFees = stripedetail.TotalFees;
                model.Tax = stripedetail.Tax;
                model.ApplicationFees = stripedetail.ApplicationFees;
                model.StripeProcessingFee = stripedetail.StripeProcessingFee;
                model.CreatedOn = stripedetail.CreatedOn.Value.ToString("dd/MM/yyyy");
                model.CreatedTime = stripedetail.CreatedOn.Value.ToString("hh:mm tt");
                model.RefundTax = stripedetail.RefundTax;
                model.RefundStripeProcessingFee = stripedetail.RefundStripeProcessingFee;
                model.TotalCaptureAmount = stripedetail.TotalCaptureAmount;
            }
            else
            {
                model.Netpayment = 0.00;
                model.TotalFees = 0.00;
                model.Tax = 0.00;
                model.ApplicationFees = 0.00;
                model.StripeProcessingFee = 0.00;
                model.RefundTax = 0.00;
                model.RefundStripeProcessingFee = 0.00;
                model.TotalCaptureAmount = 0.00;
            }
            return PartialView(model);
        }

        /// <summary>
        /// Refund Payment
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult _RefundPaymentHistory(long id)
        {
            var model = new OrderRefundHistory();
            var res = _da.GetOrderDetails(id);
            var paymentRefundDetail = _da.GetRefundDetail(id);
            ViewBag.OrderTotal = 0;
            model.CartID = id;
            ViewBag.RefundAmount = 0;
            model.RevisedFreightCharge = 0;
            if (res.Count > 0)
            {
                model.CustomerEmail = res[0].CustomerEmail;
                model.CustomerName = res[0].CustomerName;
                model.OrderDetails = res;            
                ViewBag.OrderTotal = res.Sum(s => s.RevisedPrice * s.RevisedQuantity);
                model.OrderTotal = res.Sum(s => s.RevisedPrice * s.RevisedQuantity);
                model.OrderTotal = model.OrderTotal + res[0].RevisedFreightCharge - res[0].CouponAmount;
                ViewBag.OrderTotal = model.OrderTotal;
                model.IsHasFreightCharges = res[0].IsHasFreightCharges;
                model.RevisedFreightCharge = res[0].RevisedFreightCharge;
                model.OriginalFreightCharge = res[0].OriginalFreightCharge; 
                model.CouponAmount = res[0].CouponAmount;
                model.TotalFreightDifference = res[0].OriginalFreightCharge - res[0].RevisedFreightCharge;
            }

            var stripedetail = _da.GetRefundPaymentDetail(id);
            if (stripedetail != null && stripedetail.ID != 0 && !string.IsNullOrEmpty(Convert.ToString(stripedetail.ID)))
            {  
                model.PaymentReference = stripedetail.StripeChargeID;
                model.CreatedOn = stripedetail.CreatedOn.Value.ToString("dd/MM/yyyy");
                model.CreatedTime = stripedetail.CreatedOn.Value.ToString("hh:mm tt");
            }
            else
            {              
                ViewBag.RefundAmount = 0.00;
            }
            var striperefunddetail = _da.GetRefundDetail(id);
            if (striperefunddetail != null && striperefunddetail.LogID != 0 && !string.IsNullOrEmpty(Convert.ToString(striperefunddetail.LogID)))
            {
                ViewBag.RefundAmount = striperefunddetail.RefundAmount;              
                model.RefundCreatedOn = striperefunddetail.CreatedOn.Value.ToString("dd/MM/yyyy");
                model.RefundCreatedTime = striperefunddetail.CreatedOn.Value.ToString("hh:mm tt");
                model.RefundReference = striperefunddetail.RefundId;
            }
            else
            {
               ViewBag.RefundAmount = 0.00;                
            }

            return PartialView(model);
        }

        /// <summary>
        /// Refund Payment
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult _PaymentOrderHistory(long id)

Saavi5Admin.Net/Saavi5Admin/Views/Payment/ConnectAccount.cshtml
<div style="text-align: center">
    @if (ViewBag.IsConnected == true)
    {
        <h2>You account connected successfully, account ID is <span style="background: #ddd;">@ViewBag.ConnectedAccountId</span>.</h2>
    }
    else
    {
        <h2>Failed to connect account, due to followig reason: <span style="background: #ddd;">@ViewBag.Error</span></h2>
    }
</div>

Saavi5Admin.Net/Saavi5Admin/Views/Payment/_CapturePayment.cshtml
@model DataModel.BO.PaymentBO

<script>
    $(function () {
        $("#modalmanagePayment").modal('show');
        validateForm('formPaymentAU');
        $('.groupOfTexbox').keypress(function (event) {
            return isNumber(event, this)
        });
    });
    function SuccessMethod(res) {
        if (res == "Success") {
            alert('Payment Capture Sucessfuly');
            window.location.reload();
        } else {
            growlNotification(res, 'warning', 3000);
        }
    }
    function chkAmount() {
        if ($("#txtamount").val() == "" || $("#txtamount").val() == "0") {
            $.alert('Add valid Amount');
            return false;
        }
        if ($("#hdnFlag").val() != "" && $("#hdnFlag").val() > 0 && parseFloat($("#hdnFlag").val()) < parseFloat($("#txtamount").val())) {
            $.alert('Add amount less than Authorisation Amount ' + $("#hdnFlag").val());
            return false;
        }
    }

    function isNumber(e) {
        var evt = (evt) ? evt : window.event;
        var charCode = (evt.which) ? evt.which : evt.keyCode;
        var el = $(e.target);

        if (charCode > 31 && (charCode < 48 || charCode > 57) && charCode != 46) {
            evt.preventDefault();;
        } else {
            var len = el.val().length;
            var index = el.val().indexOf('.');
            if (index >= 0 && charCode == 46) {
                evt.preventDefault();;
            }
            if (index >= 0) {
                var charAfterdot = (len + 1) - index;
                if (charAfterdot > 3) {
                    evt.preventDefault();;
                }
            }
        }
        return true;
    }

</script>

<div class="modal fade" id="modalmanagePayment" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><img src="~/Content/images/close.png"></button>
            </div>
            <div class="modal-body login">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <i class="fa fa-times" aria-hidden="true"></i>
                    </button>
                </div>
                <h2><strong>Stripe Payment Detail</strong></h2>
                <div id="divPopupMsg"></div>
                @using (Ajax.BeginForm("CapturePayment", "Payment", new AjaxOptions
                {
                    HttpMethod = "POST",
                    OnSuccess = "SuccessMethod",
                    OnBegin = "startLoading",
                    OnComplete = "stopLoading"
                }, new { id = "formPaymentAU", @class = "row" }))
                {
                    <input type="hidden" value="@ViewBag.CapturePrice" id="hdnFlag" />
                    @Html.HiddenFor(m => m.CartID)
                    @Html.HiddenFor(m => m.CustomerID)
                    @*@Html.HiddenFor(m => m.UserID)*@

                    <fieldset class="row">
                        <table>
                            <colgroup>
                                <col style="width:2%;" />
                                <col style="width:25%;" />
                                <col style="width:15%;" />
                                <col style="width:25%;" />
                                <col style="width:20%;" />
                            </colgroup>
                            <tr>

                                <td></td>
                                <td>Original Order Value:</td>
                                <td><strong>$@String.Format("{0:0.00}", ViewBag.OrderTotal)</strong></td>
                                <td>Stripe Reference:</td>
                                <td><label>@Html.DisplayFor(item => item.PaymentReference)</label></td>
                            </tr>
                            <tr>
                                <td></td>
                                <td>Pre-Authorisation Charge:</td>
                                <td>Y</td>
                                <td>Pre-Authorisation Amount:</td>
                                <td>$@String.Format("{0:0.00}", ViewBag.CapturePrice)</td>
                            </tr>
                            <tr>
                                <td></td>
                                <td>Final Charge Amount:</td>
                                <td> @Html.TextBoxFor(m => m.Amount, new { @style = "width: 80px; height: 20px;", @class = "groupOfTexbox", id = "txtamount", required = "required", maxlength = "20", ondrop = "return false;", onpaste = "return false;" })</td>
                                <td>Actual Charge Amount:</td>
                                <td>Pending</td>
                            </tr>
                            <tr>
                                <td colspan="5" style="height:20px;"></td>
                            </tr>
                            <tr>
                                <td></td>
                                <td></td>
                                <td><input type="submit" value="Charge Card" style="width:auto;" class="btn-primary" onclick="return chkAmount();" /></td>
                                <td></td>
                                <td></td>
                            </tr>
                        </table>
                    </fieldset>

                }
            </div>
        </div>
    </div>
</div>

Saavi5Admin.Net/Saavi5Admin/Views/Payment/_RefundPayment.cshtml
@model DataModel.BO.RefundBO

<script>
    $(document).ready(function () {
        $("#modalrefundPayment").modal('show');
        validateForm('formRefundPayment');
        $('.groupOfTexbox').keypress(function (event) {
            return isNumber(event, this)
        });
    });
    function SuccessMethod(res) {
        if (res == "Success") {
            alert('Refund of Payment Sucessfuly');
            window.location.reload();
        } else {
            growlNotification(res, 'warning', 3000);
        }
    }
    //function chkRefundAmount() {
    //    if ($("#txtamount").val() == "" || $("#txtamount").val() == "0") {
    //        $.alert('Add valid Amount');
    //        return false;
    //    }
    //    if ($("#hdnFlag").val() != "" && $("#hdnFlag").val() > 0 && parseFloat($("#hdnFlag").val()) < parseFloat($("#txtamount").val())) {
    //        $.alert('Add amount less than Authorisation Amount ' + $("#hdnFlag").val());
    //        return false;
    //    }
    //}



</script>

<div class="modal fade" id="modalrefundPayment" tabindex="-1" role="dialog" aria-labelledby="mynewModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><img src="~/Content/images/close.png"></button>
            </div>
            <div class="modal-body login">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <i class="fa fa-times" aria-hidden="true"></i>
                    </button>
                </div>
                <h2><strong>Stripe Payment Detail</strong></h2>
                @if (ViewBag.RefundStatus == 0)
                {
                    <div id="divPopupMsg"></div>
                    using (Ajax.BeginForm("StripeRefundPayment", "Payment", new AjaxOptions
                    {
                        HttpMethod = "POST",
                        OnSuccess = "SuccessMethod",
                        OnBegin = "startLoading",
                        OnComplete = "stopLoading"
                    }, new { id = "formRefundPayment", @class = "row" }))
                    {
                        <input type="hidden" value="@ViewBag.OrderTotal" id="hdnFlag" />
                        @Html.HiddenFor(m => m.CartID)
                        @Html.HiddenFor(m => m.CustomerID)
                        @Html.HiddenFor(m => m.UserID)
                        @Html.HiddenFor(m => m.PaymentReference)
                        @Html.HiddenFor(m => m.TotalCaptureAmount)
                        @Html.HiddenFor(m => m.Amount)


                        <fieldset class="row">
                            <table>
                                <colgroup>
                                    <col style="width:2%;" />
                                    <col style="width:25%;" />
                                    <col style="width:15%;" />
                                    <col style="width:25%;" />
                                    <col style="width:20%;" />
                                </colgroup>
                                <tr>

                                    <td></td>
                                    <td><strong>Customer Name:</strong></td>
                                    <td><strong>@Model.CustomerName</strong></td>
                                    <td></td>
                                    <td><label></label></td>
                                </tr>
                                <tr>

                                    <td></td>
                                    <td>Order Number:</td>
                                    <td><strong>@Model.CartID</strong></td>
                                    <td>Customer Email:</td>
                                    <td><label>@Model.CustomerEmail</label></td>
                                </tr>
                                <tr>

                                    <td></td>
                                    <td>Original Order Value:</td>
                                    <td> <strong>@string.Format("{0:$#,##0.00;($#,##0.00)}", ViewBag.OrderTotal)</strong></td>
                                    <td>Stripe Reference:</td>
                                    <td><label>@Html.DisplayFor(item => item.PaymentReference)</label></td>
                                </tr>
                                <tr>
                                    <td></td>
                                    <td>Date Of Charge:</td>
                                    <td><label>@Html.DisplayFor(item => item.CreatedOn)</label></td>
                                    <td>Time of Charge:</td>
                                    <td><label>@Html.DisplayFor(item => item.CreatedTime)</label></td>
                                </tr>
                                <tr>
                                    <td></td>
                                    <td>Total Fees:</td>
                                    <td><label>@string.Format("{0:$#,##0.00;($#,##0.00)}", Model.TotalFees)</label></td>
                                    <td>Stripe Processing Fee:</td>
                                    <td><label>@string.Format("{0:$#,##0.00;($#,##0.00)}", Model.StripeProcessingFee)</label></td>
                                </tr>
                                <tr>
                                    <td></td>
                                    <td>Application Fees:</td>
                                    <td><label>@string.Format("{0:$#,##0.00;($#,##0.00)}", Model.ApplicationFees)</label></td>
                                    <td>Tax:</td>
                                    <td><label>@string.Format("{0:$#,##0.00;($#,##0.00)}", Model.Tax)</label></td>
                                </tr>

                                <tr>
                                    <td></td>
                                    <td>Partial/Full Refund:</td>
                                    <td>
                                        @if (Model.PaymentClick != 1)
                                        {
                                            @Html.TextBoxFor(m => m.ShowAmount, new { @style = "width: 80px; height: 20px;", @class = "groupOfTexbox", id = "txtamount", required = "required", maxlength = "20", @readonly = "readonly", ondrop = "return false;", onpaste = "return false;" })
                                        }


                                    </td>
                                    <td>Net Payment:</td>
                                    <td> <strong>@string.Format("{0:$#,##0.00;($#,##0.00)}", Model.Netpayment)</strong></td>
                                </tr>

                                <tr>
                                    <td colspan="5" style="height:20px;"></td>
                                </tr>
                                <tr>
                                    <td></td>
                                    <td></td>
                                    <td>
                                        @if (Model.PaymentClick != 1)
                                        {
                                            <input type="submit" value="Refund Amount" id="refundclick" style="width:auto;" class="btn-primary" onclick="return chkRefundAmount();" />
                                        }
                                    </td>
                                    <td></td>
                                    <td></td>
                                </tr>

                            </table>
                        </fieldset>
                    }
                }
                else
                {
                    <input type="hidden" value="@Model.Netpayment" id="hdnFlag" />
                    @Html.HiddenFor(m => m.CartID)
                    @Html.HiddenFor(m => m.CustomerID)
                    @Html.HiddenFor(m => m.UserID)
                    @Html.HiddenFor(m => m.PaymentReference)
                    @Html.HiddenFor(m => m.TotalCaptureAmount)


                    <fieldset class="row">
                        <table>
                            <colgroup>
                                <col style="width:2%;" />
                                <col style="width:25%;" />
                                <col style="width:15%;" />
                                <col style="width:25%;" />
                                <col style="width:20%;" />
                            </colgroup>
                            <tr>

                                <td></td>
                                <td><strong>Customer Name:</strong></td>
                                <td><strong>@Model.CustomerName</strong></td>
                                <td></td>
                                <td><label></label></td>
                            </tr>
                            <tr>

                                <td></td>
                                <td>Order Number:</td>
                                <td><strong>@Model.CartID</strong></td>
                                <td>Customer Email:</td>
                                <td><label>@Model.CustomerEmail</label></td>
                            </tr>
                            <tr>

                                <td></td>
                                <td>Original Order Value:</td>
                                <td><strong>@string.Format("{0:$#,##0.00;($#,##0.00)}", ViewBag.OrderTotal)</strong></td>
                                <td>Stripe Reference:</td>
                                <td><label>@Html.DisplayFor(item => item.PaymentReference)</label></td>
                            </tr>
                            <tr>
                                <td></td>
                                <td>Date Of Charge:</td>
                                <td><label>@Html.DisplayFor(item => item.CreatedOn)</label></td>
                                <td>Time of Charge:</td>
                                <td><label>@Html.DisplayFor(item => item.CreatedTime)</label></td>
                            </tr>
                            <tr>
                                <td></td>
                                <td>Partial/Full Refund:</td>
                                <td>
                                    <label><strong>@string.Format("{0:$#,##0.00;($#,##0.00)}", ViewBag.RefundAmount)</strong></label>
                                </td>
                                <td>Stripe Refund Reference:</td>
                                <td><label>@String.Format("{0:0.00}", Model.RefundReference)</label></td>
                            </tr>
                            <tr>
                                <td></td>
                                <td>Date Of Refund:</td>
                                <td><label>@Html.DisplayFor(item => item.RefundCreatedOn)</label></td>
                                <td>Time of Refund:</td>
                                <td><label>@Html.DisplayFor(item => item.RefundCreatedTime)</label></td>
                            </tr>
                            <tr>
                                <td colspan="5" style="height:20px;"></td>
                            </tr>
                        </table>
                    </fieldset>
                }
            </div>

        </div>
    </div>
</div>